### ISSUE TITLE
Live demo site for the theme

### ISSUE THREAD

**Issue by Jieiku** [sirodoht/zola-henry#4]
How do you feel about setting up a netlify account to automatically build a demo of the theme? It is actually really easy, only takes a few minutes.

If this is not something your interested in doing, would you like me to create a mirror of the repository and create a demo that way?

**Comment by sirodoht** [comment]
Hey @Jieiku!

I've added a live demo on GitHub Pages: https://sirodoht.github.io/zola-henry/

What do you think?

**Comment by Jieiku** [comment]
Awesome! looks good here!

**Comment by Jieiku** [comment]
Now in your theme.toml just add the demo link, eg:

```toml
homepage = "https://github.com/sirodoht/zola-henry"
demo = "https://sirodoht.github.io/zola-henry/"
```

And the next time Keats updates the zola themes page, the demo link should be there.
